---
title: "Open Policing - Raleigh"
author: "Otho"
date:  "`r Sys.Date()`"
output: html_document
editor_options: 
  chunk_output_type: console
---

Reproduce Nadieh Bremer and Zan Armstrong famouse [Baby Spike visualization](https://www.visualcinnamon.com/portfolio/baby-spike)

```{r}
library(tidyverse)
library(rlang)
library(lubridate)
library(scales)
```


```{r}
dat_path <- "data/2-12-open-policing.Rdata"

# data for Raleigh, because I have been there
dat_url <- paste0("https://stacks.stanford.edu/",
                  "file/druid:tr137st9964/tr137st9964",
                  "_nc_raleigh_2019_02_25.csv.zip")

if(!file.exists(dat_path)) {
  # one temporary file zipped
  # and one with the csv
  temp <- tempfile()
  temp2 <- tempfile()
  download.file(dat_url, destfile = temp)
  
  temp2 <- unzip(temp)
  
  raleigh <- read_csv(temp2)
  
  save(raleigh, file = dat_path)
} else {
  load(dat_path)
}
```

# explore

I guess that the `time` variable is measured in seconds of the day

```{r}
raleigh$time %>% range(na.rm = TRUE)
# Time differences in secs
# [1]     1 86399
```

# Use loess.

```{r}
day_sec <- 60*60*24


# bin stops per minute
by_minute <- 
  raleigh %>%  
  mutate(mins = as_double(time) %/% 60,
         year = year(date)) %>% 
  group_by(mins, year) %>% 
  count() %>% 
  # na.omit() %>%
  # strange measurements at 0
  # probably tecnical issue
  filter(mins > 0) %>% 
  group_by(mins) %>% 
  summarise(n = mean(n))

# check
span <- 1/30
by_minute %>% 
  ggplot(aes(x = mins, y = n)) +
  stat_smooth(method = "loess", span = span) +
  geom_point(shape = ".") 

# smooth 
min_smooth <- 
  by_minute %>% 
  {loess(formula = "n ~ mins",
         data = .,
         span = span)}  %>% 
  {tibble(mins = 1:length(.$fitted),
          fitted = .$fitted)} %>% 
  full_join(by_minute, by = "mins")

# check
min_smooth %>% 
  ggplot(aes(x = mins, y = n)) +
  geom_line(aes(y = fitted)) +
  geom_point(shape = ".")

# ribbon 
med_y <- mean(min_smooth$n)
fill_up <- "#3752C3"
min_smooth %>% 
  ggplot(aes(x = mins)) +
  geom_ribbon(aes(ymax = fitted,
                  ymin = med_y),
              fill = fill_up) +
  geom_point(aes(y = n),
             colour = "grey70",
             shape = ".") +
  theme_minimal()
```

# use coordinates
Only way that I know to plot an arc.


```{r}
# to coordinates
y_from <- c(0, min_smooth$n %>% max)
y_to <- c(70, 20)

to_plot <- 
  min_smooth %>% 
  mutate(mins = rescale(mins, to = c(60, -60), from = range(mins)),
         n = rescale(n, to = y_to, from = y_from),
         fitted = rescale(fitted, to = y_to, from = y_from))
  
# save params again
med_y <- to_plot$n %>% mean
fill_up <- "#E97E00" # "#B63A82"
fill_down <- "#263A89" # "#3752C3"
ytop <- to_plot$n %>% max()
ylow <- to_plot$n %>% min()
ridge_width <- to_plot$fitted %>% range() %>% {(.[2] - .[1])/12}
grid_at <- c(med_y - ridge_width*3,
             med_y,
             med_y + ridge_width*3)
annos_color <- "grey70"

p <- 
to_plot %>% 
  ggplot(aes(x = mins,
             ymax = fitted)) +
  geom_ribbon(data = . %>%
                filter(fitted > med_y),
              ymin = med_y,
              fill = fill_up,
              # colour = colour,
              alpha = .2) +
  geom_ribbon(data = . %>%
                filter(fitted <= med_y),
              ymin = med_y,
              fill = fill_down,
              # colour = colour,
              alpha = .2)  +
  coord_map(projection = "azequidistant", orientation = c(90, -45, 225)) +
  # theme_minimal()
  theme_void()


p
```

# add gradient

```{r}
up_gradient <- function(roll, p = p) {
  p <- p + 
    geom_ribbon(data = . %>%
                  filter(fitted > med_y + ridge_width*roll),
                aes(ymin = med_y + ridge_width*roll),
                fill = fill_up,
                alpha = .3)
  return(p)
}


down_gradient <- function(roll, p = p) {
  p <- p + 
    geom_ribbon(data = . %>%
                  filter(fitted < med_y - ridge_width*roll),
                aes(ymin = med_y - ridge_width*roll),
                fill = fill_down,
                alpha = .3)
  return(p)
}

p2 <- up_gradient(1, p)
p2 <- up_gradient(2, p2)
p2 <- up_gradient(3, p2)
p2 <- up_gradient(4, p2)
p2 <- up_gradient(5, p2)
p2 <- up_gradient(6, p2)
p2 <- down_gradient(1, p2)
p2 <- down_gradient(2, p2)
p2 <- down_gradient(3, p2)
p2 <- down_gradient(4, p2)
p2 <- down_gradient(5, p2)

p2
```

# cover ribbon residues

```{r}
# Cover up ribbon residues
p3 <- 
  p2 +
  geom_ribbon(data = . %>% 
                mutate(upper_bound = case_when(fitted < med_y ~ fitted,
                                               TRUE ~ med_y)),
              aes(ymax = upper_bound,
                  ymin = ylow),
              fill = "white",
              colour = NA) +
  geom_ribbon(data = . %>% 
                mutate(lower_bound = case_when(fitted > med_y ~ fitted,
                                               TRUE ~ med_y)),
              aes(ymax = ytop,
                  ymin = lower_bound),
              fill = "white",
              colour = NA) 
  
p3

```

# add grid

```{r}

add_lines <- function(at, p) {
  p <- 
    p +
    geom_hline(yintercept = at,
               lty = 2,
               size = .1,
               colour = annos_color)

  return(p)
}

p4 <- p3
for(i in grid_at) p4 <- add_lines(at = i, p = p4)
p4


```


# add points

```{r}
p5 <- 
  p4 +
  geom_point(aes(y = n),
             colour = "grey70",
             # shape = ".",
             size = .2,
             alpha = .5) 
```

# add guides

```{r}
# add y guide
p6 <- 
  p5 + 
  geom_text(data = tibble(x = max(to_plot$mins),
                          y = grid_at),
            aes(x = x,
                y = y,
                label = y %>%
                  rescale(to = y_from, from = y_to) %>% 
                  round(1)),
            size = 4,
            nudge_x = 1,
            hjust = 1,
            vjust = 0,
            angle = max(to_plot$mins),
            colour = annos_color,
            inherit.aes = F) 

p6
```

```{r}
svglite::svglite("plots/2-12-open-policing-arc.svg")
p6
dev.off()
```

```{r}
p5 <- 
  p4 + 
  geom_hline(yintercept = med_y,
             colour =  "#0FE8FF") + #"#83D2FF" ) +
  annotate(geom = "rect",
           xmin = day_sec, xmax = day_sec + 3*10e2,
           ymin = -Inf, ymax = Inf,
           fill = "white") 
p5


```

```{r}
svglite::svglite("plots/2-12-open-policing.svg")
p6
dev.off()
```

# otherwise, map coordinates

```{r}
library(scales)

stop_coord <- 
  stop_dens %>% 
  filter(x > 0, x < 60*60*24) %>% 
  mutate(x = rescale(x, to = c(100, -10), from = range(x)),
         y = rescale(y, to = c(70, 20), from = c(0, max(y))))

fill_up <- "#3752C3"
fill_down <- "#B63A82"
colour <- "white"
ytop <- stop_coord$y %>% max()
ylow <- stop_coord$y %>% min()
med_y <- stop_coord$y %>% mean()
# Aim at 12 ridges
ridge_width <- stop_dens$y %>% range() %>% {(.[2] - .[1])/12}
grid_at <- c(med_y - ridge_width*3,
             med_y,
             med_y + ridge_width*3)
annos_color <- "grey70"

stop_coord %>%
  ggplot(aes(x = x,
             y = y)) +
  geom_ribbon(aes(ymin = med_y,
                  ymax = y)) +
  coord_map(projection = "azequidistant", orientation = c(90, 0, 225)) +
  # theme_minimal()
  theme_void()
```

