---
title: "Open Policing - Raleigh"
author: "Otho"
date:  "`r Sys.Date()`"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r}
library(tidyverse)
library(rlang)
library(lubridate)
library(scales)

# weekdays in english
Sys.setlocale("LC_TIME", "en_US.UTF8")
```


```{r}
dat_path <- "data/2-12-open-policing.Rdata"

# data for Raleigh, because I have been there
dat_url <- paste0("https://stacks.stanford.edu/",
                  "file/druid:tr137st9964/tr137st9964",
                  "_nc_raleigh_2019_02_25.csv.zip")

if(!file.exists(dat_path)) {
  # one temporary file zipped
  # and one with the csv
  temp <- tempfile()
  temp2 <- tempfile()
  download.file(dat_url, destfile = temp)
  
  temp2 <- unzip(temp)
  
  raleigh <- read_csv(temp2)
  
  save(raleigh, file = dat_path)
} else {
  load(dat_path)
}
```

# explore

I guess that the `time` variable is measured in seconds of the day

```{r}
raleigh$time %>% range(na.rm = TRUE)
# Time differences in secs
# [1]     1 86399
```

# Use loess.

```{r}
day_sec <- 60*60*24

# how many weeks in the dataset?
week_span <- raleigh$date %>%
  {lubridate::interval(start = min(.), end = max(.))} %>% 
  time_length()/(24*60*60*7) %>% 
  round()



# bin stops per minute
by_minute <- 
  raleigh %>%  
  mutate(mins = as_double(time) %/% 60,
         weekday = weekdays(date)) %>% 
  group_by(mins, weekday) %>% 
  count() %>% 
  # na.omit() %>%
  # strange measurements at 0
  # probably tecnical issue
  filter(mins > 0) %>% 
  # devide by weeks in dataset
  mutate(n = n/week_span)


# check
# span <- 1/30
span <- 1/20
by_minute %>% 
  ggplot(aes(x = mins, y = n)) +
  stat_smooth(method = "loess", span = span) +
  geom_point(shape = ".") +
  facet_grid(weekday ~ .)

by_mins_list <- 
  by_minute %>% 
  split(.$weekday)

# smooth 
smooth_obj <- 
 by_mins_list %>% 
  map(., ~loess(formula = "n ~ mins",
         data = .,
         span = span))


# prediction
preds <- 
  smooth_obj %>% 
  map(., ~predict(., se = T))
  
# join fitted values and 
# original data
min_smooth <- 
  names(preds) %>% 
  map(.x = .,
      .f = ~preds[[.x]] %>% 
      {tibble(mins = names(.$fit) %>% as.numeric(),
              fitted = .$fit,
              se = .$se,
              weekday = .x)} %>% 
        full_join(by_mins_list[[.x]])) %>% 
  reduce(bind_rows) %>% 
  # reset weekdays order %>% 
  mutate(weekday = factor(weekday, 
                          levels = c("Sunday", 
                                     "Monday",
                                     "Tuesday",
                                     "Wednesday",
                                     "Thursday",
                                     "Friday",
                                     "Saturday"))) %>% 
  # label mins and max
  group_by(weekday) %>% 
  mutate(min_max = case_when(fitted == max(fitted) ~ TRUE,
                             fitted == min(fitted) ~ TRUE,
                             TRUE ~ FALSE)) %>% 
  ungroup()

# check
min_smooth %>% 
  ggplot(aes(x = mins, y = n)) +
  geom_line(aes(y = fitted)) +
  geom_point(shape = ".") +
  facet_grid(weekday ~ .)


# try ribbon
med_y <- mean(min_smooth$n)

# cool, a bit by chance
p <- 
  min_smooth %>% 
  ggplot(aes(x = mins)) +
  geom_hline(yintercept = med_y,
             colour = "#B63A82") +
  geom_ribbon(aes(ymin = med_y,
                  ymax = fitted),
              fill = "grey80",
             colour = "#27A6D3") +
  geom_point(aes(y = n),
             shape = ".") +
  ylim(0, NA) +
  theme_minimal()
p

p + facet_grid(weekday ~ .)

fill_up <- "#3752C3"
```

# Try mirror

```{r}
p <- 
  min_smooth %>% 
  mutate(fitted_rel = fitted - med_y,
         verso = case_when(fitted_rel > 0 ~ "up",
                           TRUE ~ "down"),
         fitted_rel = abs(fitted_rel)) %>% 
  ggplot(aes(x = mins)) +
  # geom_hline(yintercept = 0) +
  geom_ribbon(aes(ymin = 0,
                  ymax = fitted_rel,
                  fill = verso),
              colour = "grey5",
              size = .3) +
  facet_grid(weekday ~ .) +
  scale_fill_manual(values = c(down = "#4C63C3AA",
                               up = "#FF6C0DAA"),
                    guide = guide_legend(nrow = 1,
                                         keyheight = unit(3, "mm"),
                                         keywidth = unit(7, "mm"))) +
  coord_cartesian(expand = FALSE) +
  theme_void()

p
```

#  label local maxima

```{r}
p1 <- 
  p + 
  geom_text(data = . %>% 
              filter(min_max),
            aes(y = fitted_rel,
                label = fitted %>% round(2)),
            colour = "grey15",
            fontface = "italic",
            vjust = 0,
            hjust = 0.2,
            size = 3,
            nudge_y = .005)

p1
```

# style

```{r}
marks_x <- seq(0, 24, by = 6)

p2 <- 
  p1 +
  scale_x_continuous(breaks = marks_x*60, 
                     labels = paste0(marks_x, "h")) +
  scale_y_continuous(breaks = 0, 
                     labels = med_y %>% round(2),
                     limits = c(0, .12)) +
  theme(axis.ticks = element_line(),
        axis.ticks.length = unit(1, "mm"),
        axis.text.x = element_text(size = unit(8, "mm")),
        axis.text.y = element_text(size = unit(8, "mm"),
                                   vjust = 0),
        legend.position = "top",
        strip.text.y = element_text(angle = 270,
                                    face = "italic",
                                    margin = margin(1,1,1,1,
                                                    unit = "mm")),
        panel.spacing = unit(0, "mm"),
        panel.border = element_rect(colour = "black", fill = NA),
        plot.margin = margin(2,2,2,2, unit = "mm"))

p2
```
